include:
  - template: Code-Quality.gitlab-ci.yml

stages:
  - build
  - test

build:
  stage: build
  image: maven:3.6.0-jdk-11-slim
  services:
    - name: docker:dind
      command: ["--tls=false"]
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2
    MAVEN_OPTS: >-
      -Dhttps.protocols=TLSv1.2
      -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
      -Dorg.slf4j.simpleLogger.showDateTime=true
      -Djava.awt.headless=true
    MAVEN_CLI_OPTS: >-
      --batch-mode
      --errors
      --fail-at-end
      --show-version
  cache:
    paths:
      - .m2/repository
  script:
    - echo "Compiling the code..."
    - 'mvn $MAVEN_CLI_OPTS clean install'
    - echo "Compile complete."